site_name: Demonstration and Testing Workplace
site_description: An introduction, writing guide, and docs testing sandbox.
site_author: Joe Wojak

theme:
  name: material
  features:
    - search.highlight

plugins:
  - search

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

copyright: Copyright &copy; 2022 Joe Wojak

nav:
  - Welcome: index.md
  - Work Experience: resume/resume.md
  - Writing Samples:
      - Introduction: samples/samples-intro.md
      - API Documentation:
          - Introduction: samples/api-intro.md
          - User Methods:
              - Create a User: samples/create-user.md
              - Update a User: samples/update-user.md
              - Delete a User: samples/delete-user.md
              - Bulk Delete Users: samples/delete-bulk.md
          - Group Methods:
              - Create a Group: samples/create-group.md
              - Update a Group: samples/update-group.md
              - List Groups: samples/list-groups.md
              - List Group Permissions: samples/list-group-permissions.md
              - Delete a Group: samples/delete-group.md
              - Bulk Delete Groups: samples/delete-groups-bulk.md
      - Budgets, Spending, and Pacing Delays:
          - Introduction: samples/budget-spend-intro.md
          - Understanding Budget Distribution and Update Cycles: samples/update-cycle.md
          - Budget Distribution Among and Within Data Centers: samples/budget-data-center.md
          - Budget Updates Can Delay Tactic Delivery: samples/budget-update.md
          - Force a Budget Update: samples/force-budget.md
      - Data Engineering Tutorial:
          - Introduction and Welcome: tutorial/welcome.md
          - Understanding Data Endpoints and Workflows: tutorial/endpoints.md
          - Configuring Your Development Environment:
              - Introduction: samples/setup-intro.md
              - Installing Scala: samples/setup-scala.md
              - Installing Java: samples/setup-java.md
              - Installing SBT: samples/setup-sbt.md
          - Create a Data Workflow Component: tutorial/create-workflow.md
          - Annotating Data: tutorial/annotate.md
          - Summary: tutorial/summary.md
      - Device Graph Overview:
          - Device Graph Basics: samples/graph-basics.md
          - Household Scores: samples/household-scores.md
          - Individual Scores: samples/individual-scores.md  
  - Writing Guide:
      - Introduction: guide/intro.md
      - Documentation Types:
          - Topic-Based Writing and Documentation Types: guide/types/types_intro.md
          - Concept Documentation: guide/types/concepts.md
          - Documentation for Simple Procedures: guide/types/tasks_simple.md
          - Documentation for Complex Procedures: guide/types/tasks_complex.md
          - Reference Documentation: guide/types/reference.md
      - Organizing Sections and Pages:
          - Introduction: guide/organization/org_intro.md
          - Section Outline: guide/organization/org_outline.md
          - Homepage:
              - Homepage Theory and Purpose: guide/organization/home_theory.md
              - Homepage Outline and Section Summaries: guide/organization/home_outline.md
              - Homepage Quick Reference: guide/organization/home_reference.md
              - Homepage Code Template: guide/organization/home_code.md
          - Overview: guide/organization/org_overview.md
          - Getting Started: guide/organization/org_getting_started.md
          - Other Content Sections: guide/organization/org_other.md
          - FAQs: guide/organization/org_faqs.md
          - ADRs: guide/organization/org_adr.md
      - API Documentation Style Guide: guide/api/api_intro.md
      - Command Line Documentation: guide/cli/cli.md
      - Styling Pages and Text:
          - Introduction: guide/style/style_intro.md
          - Bold Text: guide/style/style_bold.md
          - Code Snippets and Blocks: guide/style/style_code.md
          - Italics: guide/style/style_italics.md
          - Lists: guide/style/style_lists.md


